# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CERN.
#
# CDS-ILS is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

version: "2.3"
services:
  cache:
    image: redis:7
    restart: "always"
    read_only: true
    ports:
      - "6379:6379"
  db:
    image: postgres:14
    restart: "always"
    environment:
      - "POSTGRES_USER=invenio"
      - "POSTGRES_PASSWORD=invenio"
      - "POSTGRES_DB=invenio"
    ports:
      - "5432:5432"
  mq:
    image: rabbitmq:3-management
    restart: "always"
    ports:
      - "15672:15672"
      - "5672:5672"
  search:
    # to use ES7: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.1
    image: opensearchproject/opensearch:2.11.1
    environment:
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - discovery.type=single-node
      # Enable the following config for testing big datasets e.g 100k records
      # - cluster.routing.allocation.disk.threshold_enabled=true
      # - cluster.routing.allocation.disk.watermark.flood_stage=1gb
      # - cluster.routing.allocation.disk.watermark.low=100gb
      # - cluster.routing.allocation.disk.watermark.high=50gb
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"
      - "9300:9300"
  flower:
    image: mher/flower
    command: --broker=amqp://guest:guest@mq:5672/ --broker_api=http://guest:guest@mq:15672/api/
    ports:
      - "5555:5555"
