#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2019-2020 CERN.
#
# CDS-ILS is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

set -e

script_path=$(dirname "$0")

# Install application code and entrypoints from 'setup.py'
pip install -e $script_path/..
# Build assets
invenio collect -v
invenio webpack buildall
