#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2019-2020 CERN.
#
# CDS-ILS is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

set -e

script_path=$(dirname "$0")

export FLASK_ENV=development
export SYNDETIC_CLIENT=cernlibrary
export SERVER_NAME=localhost:5000

# Start Worker and Server
celery worker -A invenio_app.celery -l INFO & pid_celery=$!

invenio run \
  --cert "$script_path"/../docker/nginx/test.crt \
  --key "$script_path"/../docker/nginx/test.key & pid_server=$!

trap 'kill $pid_celery $pid_server &>/dev/null' EXIT

wait $pid_celery $pid_server
