#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2019-2020 CERN.
#
# CDS-ILS is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

set -e

script_path=$(dirname "$0")

export FLASK_ENV=development
export SERVER_NAME=127.0.0.1:5000

invenio run \
  --cert "$script_path"/certs/test.crt \
  --key "$script_path"/certs/test.key
