#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2019-2020 CERN.
#
# CDS-ILS is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.
if [ "$SENTRY_ENVIRONMENT" == "prod" ]
then
  echo "ERROR: you tried to run setup script on production. ABORTING."
else
  invenio setup
  invenio fixtures pages
  cds-ils fixtures vocabularies
  cds-ils fixtures location
  cds-ils migration create-unknown-reference-records
fi
