#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CERN.
#
# CDS Books is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

set -e

# Clean redis
pipenv run invenio shell --no-term-title -c "import redis; redis.StrictRedis.from_url(app.config['CACHE_REDIS_URL']).flushall(); print('Cache cleared')"
pipenv run invenio db destroy --yes-i-know
pipenv run invenio db init create
pipenv run invenio index destroy --force --yes-i-know
pipenv run invenio index init --force
pipenv run invenio index queue init purge

# Create roles to restrict access
pipenv run invenio roles create admin
pipenv run invenio roles create librarian

# create users
pipenv run invenio users create patron1@test.ch -a --password=123456 # ID 1
pipenv run invenio users create patron2@test.ch -a --password=123456 # ID 2
pipenv run invenio users create admin@test.ch -a --password=123456 # ID 3
pipenv run invenio users create librarian@test.ch -a --password=123456 # ID 4

# assign roles
pipenv run invenio roles add admin@test.ch admin
pipenv run invenio roles add librarian@test.ch librarian
# assign actions
pipenv run invenio access allow superuser-access role admin
pipenv run invenio access allow ils-backoffice-access role librarian

# Create ILS demo data
pipenv run ils demo data
